
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "Z:/VS/Project/axmol/tools/external/cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:30 (project)"
    message: |
      The target system is: WindowsStore - 10.0 - 
      The host system is: Windows - 10.0.19045 - AMD64
...
