
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "Z:/VS/Project/axmol/tools/external/cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:30 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
